# =============================================================================
# Docker Compose - Base Services
# =============================================================================
# Usage (run from infra/compose folder):
#   docker compose -f base.compose.yml -f dev.compose.yml up
#
# With observability:
#   docker compose -f base.compose.yml -f dev.compose.yml -f otel.compose.yml up
#
# Production:
#   docker compose -f base.compose.yml -f prod.compose.yml up
#
# Note: .env file is in this folder (infra/compose/)
# =============================================================================

services:
  # ---------------------------------------------------------------------------
  # Nginx - Reverse Proxy
  # ---------------------------------------------------------------------------
  nginx:
    image: nginx:alpine
    ports:
      - "8319:80"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - web
    networks:
      - app-network

  # ---------------------------------------------------------------------------
  # API - NestJS Backend
  # ---------------------------------------------------------------------------
  api:
    build:
      context: ../../apps/api
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${PORT:-3000}
      # Encryption (for connection credentials at rest)
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      # Database connection (individual variables)
      - POSTGRES_HOST=${POSTGRES_HOST:-db}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-appdb}
      - POSTGRES_SSL=${POSTGRES_SSL:-false}
      # LLM Settings
      - LLM_DEFAULT_PROVIDER=${LLM_DEFAULT_PROVIDER}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - ANTHROPIC_MODEL=${ANTHROPIC_MODEL}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_DEPLOYMENT=${AZURE_OPENAI_DEPLOYMENT}
      - AZURE_OPENAI_API_VERSION=${AZURE_OPENAI_API_VERSION} 
      # JWT
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ACCESS_TTL_MINUTES=${JWT_ACCESS_TTL_MINUTES:-15}
      - JWT_REFRESH_TTL_DAYS=${JWT_REFRESH_TTL_DAYS:-14}
      # OAuth
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}
      # AWS
      - S3_BUCKET=${S3_BUCKET}
      - S3_REGION=${S3_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      # Admin bootstrap
      - INITIAL_ADMIN_EMAIL=${INITIAL_ADMIN_EMAIL}
      # Observability
      - OTEL_ENABLED=${OTEL_ENABLED:-false}
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
      - OTEL_SERVICE_NAME=${OTEL_SERVICE_NAME:-enterprise-app-api}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      # Graph Database (Neo4j)
      - NEO4J_HOST=${NEO4J_HOST:-neo4j}
      - NEO4J_PORT=${NEO4J_PORT:-7687}
      - NEO4J_USER=${NEO4J_USER:-neo4j}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD:-neo4j}
    depends_on:
      db:
        condition: service_healthy
      neo4j:
        condition: service_healthy
    networks:
      - app-network

  # ---------------------------------------------------------------------------
  # Web - React Frontend
  # ---------------------------------------------------------------------------
  web:
    build:
      context: ../../apps/web
      dockerfile: Dockerfile
    networks:
      - app-network

  # ---------------------------------------------------------------------------
  # Database - PostgreSQL
  # ---------------------------------------------------------------------------
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-appdb}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  # ---------------------------------------------------------------------------
  # Graph Database - Neo4j
  # ---------------------------------------------------------------------------
  neo4j:
    image: neo4j:5-community
    environment:
      - NEO4J_AUTH=${NEO4J_USER:-neo4j}/${NEO4J_PASSWORD:-neo4j}
    volumes:
      - neo4j-data:/data
    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -u ${NEO4J_USER:-neo4j} -p ${NEO4J_PASSWORD:-neo4j} 'RETURN 1'"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - app-network

# =============================================================================
# Networks
# =============================================================================
networks:
  app-network:
    driver: bridge

# =============================================================================
# Volumes
# =============================================================================
volumes:
  postgres-data:
  neo4j-data:
