# =============================================================================
# Docker Compose - Development Overrides
# =============================================================================
# Usage:
#   docker compose -f base.compose.yml -f dev.compose.yml up
#
# Provides development-specific settings: hot reload, exposed ports, volumes.
# =============================================================================

services:
  # ---------------------------------------------------------------------------
  # API - Development overrides
  # ---------------------------------------------------------------------------
  api:
    build:
      target: development
    volumes:
      - ../../apps/api/src:/app/src:ro
      - ../../apps/api/prisma:/app/prisma:ro
    environment:
      - NODE_ENV=development
      - NODE_OPTIONS=--max-old-space-size=4096
    extra_hosts:
      - "pgadmin.local:host-gateway"
    command: npm run start:dev

  # ---------------------------------------------------------------------------
  # Web - Development overrides
  # ---------------------------------------------------------------------------
  web:
    build:
      target: development
    volumes:
      - ../../apps/web/src:/app/src:ro
    environment:
      - NODE_ENV=development
    command: npm run dev

  # ---------------------------------------------------------------------------
  # Database - Expose port for local tools
  # ---------------------------------------------------------------------------
  db:
    ports:
      - "5432:5432"

  # ---------------------------------------------------------------------------
  # Neo4j - Expose ports for local tools
  # ---------------------------------------------------------------------------
  neo4j:
    ports:
      - "7474:7474"
      - "7687:7687"

  # ---------------------------------------------------------------------------
  # PgAdmin - PostgreSQL Web UI (dev only)
  # ---------------------------------------------------------------------------
  pgadmin:
    image: dpage/pgadmin4:8
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-admin@local.dev}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-admin}
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ../pgadmin/servers.json:/pgadmin4/servers.json:ro
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

volumes:
  pgadmin-data:
